name: learn-github-actions
run-name: ${{ github.actor }} pushed a new commit
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello, world!"