name: learn-github-actions
run-name: ${{ github.actor }} pushed a new commit
on: [push]
jobs:
  run-pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Show python version before conda install
        run: python --version
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: sudoku
          environment-file: ./impl/python/environment.yaml
          python-version: 3.9
          auto-activate-base: false
      - name: Apply linter (flake 8)
        shell: bash -l {0}
        run: |
            python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run pytest
        shell: bash -l {0}
        run: |
            pytest