name: learn-github-actions
run-name: ${{ github.actor }} pushed a new commit
on: [push]
jobs:
  run-pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: s-weigand/setup-conda@v1
      with:
        activate-conda: false
    - run: conda --version
    - run: which python
    - name: Create conda environment
      working-directory: ./impl/python
      run: |
        conda env create -f environment.yaml
        conda activate sudoku
    - name: Run pytest
      working-directory: ./impl/python
      run: |
        pytest